server:
  port: 8096
  servlet:
    context-path: /openai-migration
spring:
  application:
    name: openai-migration-poc

langchain4j:
  open-ai:
    chat-model:
      api-key: demo

#sourcePath: D:\micronaut\customer validation with database\Customer-Validation\src
sourcePath: src/main/resources/src
destinationPath: /micronaut-To-Spring-boot-Test-Project



